version: "3"
services:
  db:
    container_name: db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  ban-bin:
    container_name: ban-bin
    image: latest/ban-bin
    restart: always
    build: ./ban-bin
    ports:
      - "7500:7500"
    depends_on: 
      - db
  ban-ban:
    container_name: ban-ban
    image: latest/ban-ban
    restart: always
    build: ./ban-ban
    ports:
      - "5173:5173"
    depends_on: 
      - ban-bin